<?php
/**
 * FX - fileXperience – Language strings
 *
 * Access pattern examples:
 *   app_text('setup.title')              // current language
 *   app_text('de.setup.title')           // explicit language
 *   app_text('upload.error_invalid_link')
 */
return [
    'en' => [
        'language' => 'English',
        'app' => [
            'name' => 'FX - fileXperience',
            'brand' => '◈ FX - fileXperience',
        ],
        'common' => [
            'back' => '← Back',
            'next' => 'Next →',
            'optional' => 'optional',
            'remove' => 'Remove',
            'token' => 'Token',
            'expired' => 'Expired',
            'download' => 'Download',
            'or' => 'or',
        ],
        'setup' => [
            'page_title' => 'FX - fileXperience – Setup',
            'title' => 'Setup',
            'subtitle' => 'Set language, transfer settings, passwords and optional IP whitelist. This page appears only once.',
            'step_config' => 'Configuration',
            'step_passwords' => 'Passwords',
            'step_whitelist' => 'Whitelist',
            'section_language' => 'Language',
            'language_label' => 'Interface language',
            'section_config' => 'Transfer settings',
            'base_url_label' => 'BASE_URL',
            'base_url_hint' => 'Full public URL to this folder, without trailing slash.',
            'base_url_placeholder' => 'https://example.com/fx-filexperience',
            'token_ttl_label' => 'Token TTL in seconds',
            'token_ttl_hint' => 'How long a QR/upload session remains valid.',
            'cron_secret_label' => 'Cron secret',
            'cron_secret_hint' => 'Secret for cron.php?secret=... Use a long random value.',
            'cron_secret_placeholder' => 'long-random-secret',
            'section_credentials' => 'Access credentials',
            'public_access_warning' => 'If you do not create any password here and leave the whitelist empty, this installation will be usable by anyone who finds or guesses the URL. If you add whitelist entries, only these trusted clients may create new QR sessions.',
            'password_label_name' => 'Label',
            'password_label_placeholder' => 'e.g. Private',
            'password_value' => 'Password',
            'password_confirm' => 'Repeat',
            'add_password' => '+ Add another password',
            'section_whitelist' => 'IP / host whitelist',
            'whitelist_optional' => 'optional',
            'whitelist_hint' => 'Entries in this list may create new QR sessions without a password. If no password is configured, this whitelist becomes the access restriction for the PC page. The upload link itself remains token-based so phones outside the same network can still upload after scanning the QR code.',
            'whitelist_placeholder' => 'e.g. 192.168.1.1 or vpn.example.com',
            'add_whitelist' => '+ Add entry',
            'finish' => 'Finish setup ✓',
            'validation_language' => 'Selected language is not available.',
            'validation_base_url_required' => 'BASE_URL is required.',
            'validation_base_url_scheme' => 'BASE_URL must start with http:// or https://.',
            'validation_token_ttl' => 'Token TTL must be between 30 and 86400 seconds.',
            'validation_cron_secret' => 'Cron secret must contain at least 12 characters.',
                        'validation_password_label' => 'Password {number}: Please enter a label.',
            'validation_password_length' => '"{label}": Password must contain at least 8 characters.',
            'validation_password_match' => '"{label}": Passwords do not match.',
            'write_error' => 'Error writing config.inc.php — please check write permissions (chmod 664).',
            'js_password_label' => 'Label',
            'js_password_label_placeholder' => 'e.g. Work',
            'js_password_value' => 'Password',
            'js_password_confirm' => 'Repeat',
            'js_whitelist_placeholder' => 'e.g. 192.168.1.1 or vpn.example.com',
        ],
        'access_denied' => [
            'page_title' => 'FX - fileXperience – Access denied',
            'title' => 'Access denied',
            'subtitle' => 'This installation is restricted to trusted clients.',
            'message' => 'Your current connection is not on the configured IP/host whitelist. Open FX - fileXperience from an approved network or adjust the setup configuration.',
        ],
        'login' => [
            'page_title' => 'FX - fileXperience – Login',
            'title' => 'Login',
            'subtitle' => 'Enter the password to continue.',
            'password_label' => 'Password',
            'button' => 'Continue →',
            'error' => 'Wrong password. Please try again.',
        ],
        'main' => [
            'page_title' => 'FX - fileXperience – Waiting for upload',
            'title' => 'Get a file from your phone',
            'subtitle' => 'Scan QR code, upload file – done.',
            'step_opened' => 'QR generated',
            'step_scan' => 'Scan QR & upload',
            'step_download' => 'Download',
            'qr_label' => 'Scan with phone camera',
            'status_waiting_title' => 'Waiting for upload …',
            'status_waiting_sub' => 'Point your camera at the QR code',
            'download_button' => '⬇ Download file',
            'new_session' => '+ Start new session',
            'session_expired_title' => 'Session expired',
            'session_expired_sub' => 'Please start a new session',
            'file_ready_title' => 'File ready!',
            'qr_hidden_title' => 'Upload received.',
            'qr_hidden_sub' => 'The QR code is no longer valid. Download the file to start a new session automatically.',
            'downloaded_title' => 'File downloaded.',
            'downloaded_sub' => 'Starting a new session …',
            'new_session_after_download' => 'Starting new session …',
            'config_missing_title' => 'Configuration missing',
        ],
        'upload' => [
            'page_title' => 'FX - fileXperience – Upload',
            'title' => 'Upload file',
            'subtitle' => 'The file is transferred directly to the PC.',
            'drop_text' => 'Tap to select',
            'drop_hint' => 'Everything except executable files · max. {mb} MB',
            'upload_button' => 'Upload',
            'uploading' => 'Uploading …',
            'success_title' => 'Uploaded!',
            'success_sub' => 'You can now download it on the PC.',
            'new_scan' => '📷 New upload',
            'ttl_label' => 'Token valid for:',
            'scanner_title' => '◈ FX - fileXperience',
            'scanner_sub' => 'Point your camera at the new QR code on the PC screen',
            'scanner_starting' => 'Starting camera …',
            'scanner_hold' => 'Hold the QR code inside the frame …',
            'scanner_found' => '✓ Code detected – loading …',
            'scanner_missing_library' => 'Local QR library could not be loaded. Please check whether assets/vendor/jsqr/jsQR.js was uploaded.',
            'scanner_camera_error' => 'Camera not available: {message}',
            'cancel' => 'Cancel',
            'error_invalid_link_title' => 'Invalid or expired link',
            'error_invalid_link_msg' => 'Please start a new session on the PC and scan the QR code again.',
            'error_token_expired' => 'Session expired. Please scan the QR code again.',
            'error_too_large' => 'File too large (max. {mb} MB)',
            'error_blocked_ext' => '.{ext} files are not allowed for security reasons.',
            'error_save' => 'Error saving file. Please try again.',
            'error_ini_size' => 'File exceeds server limit',
            'error_form_size' => 'File too large',
            'error_partial' => 'Upload incomplete – please try again',
            'error_no_file' => 'No file selected',
            'error_no_tmp_dir' => 'Server configuration error (missing tmp directory)',
            'error_cant_write' => 'Write error on the server',
            'error_unknown' => 'Unknown error (code {code})',
            'expired' => 'expired',
        ],
        'download' => [
            'invalid_token' => 'Invalid or expired token.',
            'no_file' => 'No file available for this token.',
            'file_missing' => 'File no longer exists.',
        ],
        'poll' => [
            'invalid_token' => 'Invalid token',
        ],
        'cron' => [
            'forbidden' => 'Forbidden',
            'token_removed' => 'Token removed: {token} (created {time})',
            'orphan_deleted' => 'Orphaned file deleted: {file}',
            'expired_file_deleted' => 'File for expired token deleted: {file}',
            'summary' => '[{time}] Cleanup: {tokens} token(s) removed from JSON, {files} file(s) deleted.',
        ],
        'config' => [
            'base_url_missing' => 'BASE_URL is not set. Run setup again or add it to config.inc.php.',
            'base_url_scheme' => 'BASE_URL must start with http:// or https://.',
            'tokens_dir_missing' => 'Token directory does not exist.',
            'tokens_open_error' => 'tokens.json cannot be opened.',
            'tokens_lock_error' => 'tokens.json could not be locked.',
        ],
    ],
    'de' => [
        'language' => 'Deutsch',
        'app' => [
            'name' => 'FX - fileXperience',
            'brand' => '◈ FX - fileXperience',
        ],
        'common' => [
            'back' => '← Zurück',
            'next' => 'Weiter →',
            'optional' => 'optional',
            'remove' => 'Entfernen',
            'token' => 'Token',
            'expired' => 'Abgelaufen',
            'download' => 'Download',
            'or' => 'oder',
        ],
        'setup' => [
            'page_title' => 'FX - fileXperience – Ersteinrichtung',
            'title' => 'Ersteinrichtung',
            'subtitle' => 'Lege Sprache, Transfer-Einstellungen, Passwörter und optionale IP-Whitelist fest. Diese Seite erscheint nur einmal.',
            'step_config' => 'Konfiguration',
            'step_passwords' => 'Passwörter',
            'step_whitelist' => 'Whitelist',
            'section_language' => 'Sprache',
            'language_label' => 'Oberflächensprache',
            'section_config' => 'Transfer-Einstellungen',
            'base_url_label' => 'BASE_URL',
            'base_url_hint' => 'Vollständige öffentliche URL zu diesem Ordner, ohne Slash am Ende.',
            'base_url_placeholder' => 'https://example.com/fx-filexperience',
            'token_ttl_label' => 'Token-TTL in Sekunden',
            'token_ttl_hint' => 'Wie lange eine QR-/Upload-Session gültig bleibt.',
            'cron_secret_label' => 'Cron-Secret',
            'cron_secret_hint' => 'Secret für cron.php?secret=... Nutze einen langen Zufallswert.',
            'cron_secret_placeholder' => 'langes-zufaelliges-secret',
            'section_credentials' => 'Zugangsdaten',
            'public_access_warning' => 'Wenn du hier kein Passwort anlegst und die Whitelist leer lässt, kann diese Installation künftig von jedem genutzt werden, der die URL findet oder errät. Wenn du Whitelist-Einträge setzt, dürfen nur diese vertrauenswürdigen Anschlüsse neue QR-Sessions erzeugen.',
            'password_label_name' => 'Bezeichnung',
            'password_label_placeholder' => 'z. B. Privat',
            'password_value' => 'Passwort',
            'password_confirm' => 'Wiederholen',
            'add_password' => '+ Weiteres Passwort hinzufügen',
            'section_whitelist' => 'IP / Host-Whitelist',
            'whitelist_optional' => 'optional',
            'whitelist_hint' => 'Einträge aus dieser Liste dürfen ohne Passwort neue QR-Sessions erzeugen. Wenn kein Passwort eingerichtet ist, wird diese Whitelist zur Zugriffsbeschränkung für die PC-Seite. Der Upload-Link bleibt nur tokenbasiert, damit Smartphones außerhalb desselben Netzwerks nach dem QR-Scan trotzdem hochladen können.',
            'whitelist_placeholder' => 'z. B. 192.168.1.1 oder vpn.example.com',
            'add_whitelist' => '+ Eintrag hinzufügen',
            'finish' => 'Einrichtung abschließen ✓',
            'validation_language' => 'Die gewählte Sprache ist nicht verfügbar.',
            'validation_base_url_required' => 'BASE_URL ist erforderlich.',
            'validation_base_url_scheme' => 'BASE_URL muss mit http:// oder https:// beginnen.',
            'validation_token_ttl' => 'Token-TTL muss zwischen 30 und 86400 Sekunden liegen.',
            'validation_cron_secret' => 'Cron-Secret muss mindestens 12 Zeichen enthalten.',
                        'validation_password_label' => 'Passwort {number}: Bitte einen Namen vergeben.',
            'validation_password_length' => '"{label}": Passwort muss mindestens 8 Zeichen haben.',
            'validation_password_match' => '"{label}": Passwörter stimmen nicht überein.',
            'write_error' => 'Fehler beim Schreiben von config.inc.php — bitte Schreibrechte prüfen (chmod 664).',
            'js_password_label' => 'Bezeichnung',
            'js_password_label_placeholder' => 'z. B. Arbeit',
            'js_password_value' => 'Passwort',
            'js_password_confirm' => 'Wiederholen',
            'js_whitelist_placeholder' => 'z. B. 192.168.1.1 oder vpn.example.com',
        ],
        'access_denied' => [
            'page_title' => 'FX - fileXperience – Zugriff verweigert',
            'title' => 'Zugriff verweigert',
            'subtitle' => 'Diese Installation ist auf vertrauenswürdige Anschlüsse beschränkt.',
            'message' => 'Deine aktuelle Verbindung steht nicht auf der eingerichteten IP-/Host-Whitelist. Öffne FX - fileXperience aus einem freigegebenen Netzwerk oder passe die Setup-Konfiguration an.',
        ],
        'login' => [
            'page_title' => 'FX - fileXperience – Anmeldung',
            'title' => 'Anmeldung',
            'subtitle' => 'Bitte Passwort eingeben, um fortzufahren.',
            'password_label' => 'Passwort',
            'button' => 'Weiter →',
            'error' => 'Falsches Passwort. Bitte erneut versuchen.',
        ],
        'main' => [
            'page_title' => 'FX - fileXperience – Warte auf Upload',
            'title' => 'Datei vom Handy holen',
            'subtitle' => 'QR-Code scannen, Datei hochladen – fertig.',
            'step_opened' => 'QR generiert',
            'step_scan' => 'QR scannen & hochladen',
            'step_download' => 'Download',
            'qr_label' => 'Mit Handy-Kamera scannen',
            'status_waiting_title' => 'Warte auf Upload …',
            'status_waiting_sub' => 'Halte die Kamera auf den QR-Code',
            'download_button' => '⬇ Datei herunterladen',
            'new_session' => '+ Neue Session starten',
            'session_expired_title' => 'Session abgelaufen',
            'session_expired_sub' => 'Bitte neue Session starten',
            'file_ready_title' => 'Datei bereit!',
            'qr_hidden_title' => 'Upload empfangen.',
            'qr_hidden_sub' => 'Der QR-Code ist jetzt ungültig. Nach dem Download startet automatisch eine neue Session.',
            'downloaded_title' => 'Datei heruntergeladen.',
            'downloaded_sub' => 'Neue Session wird gestartet …',
            'new_session_after_download' => 'Neue Session wird gestartet …',
            'config_missing_title' => 'Konfiguration fehlt',
        ],
        'upload' => [
            'page_title' => 'FX - fileXperience – Hochladen',
            'title' => 'Datei hochladen',
            'subtitle' => 'Die Datei wird direkt zum PC übertragen.',
            'drop_text' => 'Tippen zum Auswählen',
            'drop_hint' => 'Alles außer ausführbaren Dateien · max. {mb} MB',
            'upload_button' => 'Hochladen',
            'uploading' => 'Wird hochgeladen …',
            'success_title' => 'Hochgeladen!',
            'success_sub' => 'Du kannst jetzt am PC downloaden.',
            'new_scan' => '📷 Neuer Upload',
            'ttl_label' => 'Token gültig für:',
            'scanner_title' => '◈ FX - fileXperience',
            'scanner_sub' => 'Halte die Kamera auf den neuen QR-Code am PC-Bildschirm',
            'scanner_starting' => 'Kamera wird gestartet …',
            'scanner_hold' => 'QR-Code in den Rahmen halten …',
            'scanner_found' => '✓ Code erkannt – wird geladen …',
            'scanner_missing_library' => 'Lokale QR-Bibliothek konnte nicht geladen werden. Bitte prüfen, ob assets/vendor/jsqr/jsQR.js mit hochgeladen wurde.',
            'scanner_camera_error' => 'Kamera nicht verfügbar: {message}',
            'cancel' => 'Abbrechen',
            'error_invalid_link_title' => 'Ungültiger oder abgelaufener Link',
            'error_invalid_link_msg' => 'Bitte am PC eine neue Session starten und den QR-Code erneut scannen.',
            'error_token_expired' => 'Session abgelaufen. Bitte QR-Code neu scannen.',
            'error_too_large' => 'Datei zu groß (max. {mb} MB)',
            'error_blocked_ext' => '.{ext}-Dateien sind aus Sicherheitsgründen nicht erlaubt.',
            'error_save' => 'Fehler beim Speichern. Bitte erneut versuchen.',
            'error_ini_size' => 'Datei überschreitet Server-Limit',
            'error_form_size' => 'Datei zu groß',
            'error_partial' => 'Upload unvollständig – bitte erneut versuchen',
            'error_no_file' => 'Keine Datei ausgewählt',
            'error_no_tmp_dir' => 'Serverkonfigurationsfehler (kein tmp-Verzeichnis)',
            'error_cant_write' => 'Schreibfehler auf dem Server',
            'error_unknown' => 'Unbekannter Fehler (Code {code})',
            'expired' => 'abgelaufen',
        ],
        'download' => [
            'invalid_token' => 'Ungültiger oder abgelaufener Token.',
            'no_file' => 'Keine Datei für diesen Token vorhanden.',
            'file_missing' => 'Datei nicht mehr vorhanden.',
        ],
        'poll' => [
            'invalid_token' => 'Ungültiger Token',
        ],
        'cron' => [
            'forbidden' => 'Forbidden',
            'token_removed' => 'Token entfernt: {token} (erstellt {time})',
            'orphan_deleted' => 'Verwaiste Datei gelöscht: {file}',
            'expired_file_deleted' => 'Datei zu abgelaufenem Token gelöscht: {file}',
            'summary' => '[{time}] Cleanup: {tokens} Token(s) aus JSON entfernt, {files} Datei(en) gelöscht.',
        ],
        'config' => [
            'base_url_missing' => 'BASE_URL ist nicht gesetzt. Setup erneut ausführen oder in config.inc.php ergänzen.',
            'base_url_scheme' => 'BASE_URL muss mit http:// oder https:// beginnen.',
            'tokens_dir_missing' => 'Token-Verzeichnis existiert nicht.',
            'tokens_open_error' => 'tokens.json kann nicht geöffnet werden.',
            'tokens_lock_error' => 'tokens.json konnte nicht gesperrt werden.',
        ],
    ],
];
